#!/bin/sh

SOURCE_ICON=$1

#generate ios app icons
convert -resize 57x57 $SOURCE_ICON resources/ios/Images.xcassets/AppIcon.appiconset/icon57.png
convert -resize 72x72 $SOURCE_ICON resources/ios/Images.xcassets/AppIcon.appiconset/icon72.png
convert -resize 76x76 $SOURCE_ICON resources/ios/Images.xcassets/AppIcon.appiconset/icon76.png
convert -resize 114x114 $SOURCE_ICON resources/ios/Images.xcassets/AppIcon.appiconset/icon114.png
convert -resize 120x120 $SOURCE_ICON resources/ios/Images.xcassets/AppIcon.appiconset/icon120.png
convert -resize 144x144 $SOURCE_ICON resources/ios/Images.xcassets/AppIcon.appiconset/icon144.png
convert -resize 152x152 $SOURCE_ICON resources/ios/Images.xcassets/AppIcon.appiconset/icon152.png


#generate tizen app icon
convert -resize 117x117 $SOURCE_ICON tmp.png
convert -size 117x117 xc:none -fill tmp.png -draw "circle 58.5,58.5 58.5,2" resources/tizen/app-icon.png
rm tmp.png

#generate tizen store icon
convert -resize 512x512 $SOURCE_ICON tmp.png
convert -size 512x512 xc:none -fill tmp.png -draw "circle 256,256 256,2" resources/tizen/store-icon.png
rm tmp.png