#!/bin/sh

SOURCE_ICON=$1

#generate tizen icon
convert -resize 117x117 $SOURCE_ICON tmp.png
convert -size 117x117 xc:none -fill tmp.png -draw "circle 58.5,58.5 58.5,0" resources/tizen/icon.png
rm tmp.png